
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${ENV_TEST} .env-test
  script:
    - docker build -t booking-api-image .
    - echo "Build image complete."



deploy-job:
  stage: deploy
  script:
    - docker compose up -f docker-compose-ci.yml -d
    - echo "Application successfully deployed."
