services:
  booking_back_service:
    container_name: 'booking_back'
    image: booking-api-image:latest
    ports:
      - "7777:8000"
    networks:
      - myNetwork
   
    volumes:
      - shared-images:/app/src/static/images
  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    image: booking-api-image:latest
    networks:
      - myNetwork
    depends_on:
      - booking_back_service
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"
   
    volumes:
      - shared-images:/app/src/static/images

  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    image: booking-api-image:latest
    networks:
      - myNetwork
    depends_on:
      - booking_back_service
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

networks:
  myNetwork:
    external: true

volumes:
  shared-images:
