services:
  booking_db_service:
    image: postgres:16
    container_name: booking_db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - myNetwork
    volumes:
      - pg-booking-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  booking_cache_service:
    image: redis:7.4
    container_name: booking_cache
    ports:
      - "7379:6379"
    networks:
      - myNetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  booking_back_service:
    container_name: 'booking_back'
    image: booking-api-image:latest
    ports:
      - "7777:8000"
    networks:
      - myNetwork
   
    volumes:
      - shared-images:/app/src/static/images
  booking_nginx:
    image: nginx:latest
    container_name: booking_nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - myNetwork
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
      - ./web_nginx:/var/www/html:ro  
    depends_on:
      - booking_back_service  
    restart: unless-stopped

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    image: booking-api-image:latest
    networks:
      - myNetwork
    depends_on:
      - booking_back_service
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"
   
    volumes:
      - shared-images:/app/src/static/images

  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    image: booking-api-image:latest
    networks:
      - myNetwork
    depends_on:
      - booking_back_service
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

networks:
  myNetwork:
    external: true

volumes:
  pg-booking-data:
  shared-images:
